# Generated by Django 6.0.2 on 2026-03-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('publish_article', 'Puede publicar artículos'), ('feature_article', 'Puede destacar artículos')]},
        ),
    ]
